# -*- coding: utf-8 -*-
"""Corner case generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eYf80HktVwdtWVWdd1FRo7EqDCAvKOEB
"""

import argparse
import os
from urllib.parse import urlparse

import numpy as np
import torch
from PIL import Image, ImageDraw

from diffusers import (
    ControlNetModel,
    StableDiffusionControlNetInpaintPipeline,
    DDIMScheduler,
)
from diffusers.utils import load_image


def make_inpaint_condition(image: Image.Image, mask_image: Image.Image) -> torch.Tensor:
    """
    Build the ControlNet 'control_image' tensor for inpainting:
    - normalize image to [0,1]
    - normalize mask to [0,1]
    - set masked pixels to -1.0
    Pattern matches the official example for control_v11p_sd15_inpaint. :contentReference[oaicite:2]{index=2}
    """
    image_np = np.array(image.convert("RGB")).astype(np.float32) / 255.0
    mask_np = np.array(mask_image.convert("L")).astype(np.float32) / 255.0
    assert image_np.shape[0:2] == mask_np.shape[0:2], "image and mask must have same HxW"

    image_np[mask_np > 0.5] = -1.0
    image_np = np.expand_dims(image_np, 0).transpose(0, 3, 1, 2)
    return torch.from_numpy(image_np)

def preset_mask(name: str, size=(512, 512)) -> Image.Image:
    """
    White = editable/inpaint region
    Black = preserve region
    """
    w, h = size
    mask = Image.new("L", (w, h), 0)
    draw = ImageDraw.Draw(mask)

    def rect(x0f, y0f, x1f, y1f):
        draw.rectangle(
            [int(x0f * w), int(y0f * h), int(x1f * w), int(y1f * h)],
            fill=255
        )

    def ellipse(x0f, y0f, x1f, y1f):
        draw.ellipse(
            [int(x0f * w), int(y0f * h), int(x1f * w), int(y1f * h)],
            fill=255
        )

    # Ground / floor-like regions
    if name == "ground_center":
        rect(0.25, 0.72, 0.75, 0.98)

    elif name == "ground_left":
        rect(0.02, 0.72, 0.42, 0.98)

    elif name == "ground_right":
        rect(0.58, 0.72, 0.98, 0.98)

    elif name == "ground_band":
        rect(0.00, 0.72, 1.00, 0.98)

    elif name == "ground_center_wide":
        rect(0.15, 0.70, 0.85, 0.98)

    # Middle regions
    elif name == "middle_center":
        rect(0.28, 0.35, 0.72, 0.72)

    elif name == "middle_left":
        rect(0.02, 0.35, 0.42, 0.72)

    elif name == "middle_right":
        rect(0.58, 0.35, 0.98, 0.72)

    elif name == "middle_band":
        rect(0.00, 0.35, 1.00, 0.72)

    # Top regions
    elif name == "top_center":
        rect(0.28, 0.02, 0.72, 0.30)

    elif name == "top_left":
        rect(0.02, 0.02, 0.42, 0.30)

    elif name == "top_right":
        rect(0.58, 0.02, 0.98, 0.30)

    elif name == "top_band":
        rect(0.00, 0.00, 1.00, 0.30)

    # Side regions
    elif name == "left_band":
        rect(0.00, 0.00, 0.30, 1.00)

    elif name == "right_band":
        rect(0.70, 0.00, 1.00, 1.00)

    # Central box
    elif name == "center_box":
        rect(0.20, 0.20, 0.80, 0.80)

    # Spill / puddle shapes
    elif name == "puddle_center":
        ellipse(0.30, 0.78, 0.70, 0.95)

    elif name == "puddle_left":
        ellipse(0.05, 0.78, 0.40, 0.95)

    elif name == "puddle_right":
        ellipse(0.60, 0.78, 0.95, 0.95)

    # Vertical/taller shape for fire/smoke near a machine/car
    elif name == "vertical_center":
        rect(0.38, 0.30, 0.62, 0.92)

    elif name == "vertical_left":
        rect(0.10, 0.30, 0.34, 0.92)

    elif name == "vertical_right":
        rect(0.66, 0.30, 0.90, 0.92)

    else:
        raise ValueError(
            f"Unknown mask preset: {name}. "
            f"Try ground_center, ground_left, ground_right, middle_center, "
            f"top_center, left_band, right_band, puddle_center, vertical_center."
        )

    return mask


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--prompt", type=str, required=True)
    parser.add_argument("--imageURL", type=str, required=True)
    parser.add_argument("--container_name", type=str, required=True)
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--negative_prompt", type=str, default="lowres, blurry, bad anatomy, artifacts")
    parser.add_argument("--steps", type=int, default=25)
    parser.add_argument("--guidance", type=float, default=7.5)
    parser.add_argument("--maskURL", type=str, default=None)
    parser.add_argument("--mask_path", type=str, default=None)
    parser.add_argument("--mask_preset", type=str, default=None) # Added mask preset argument
    parser.add_argument("--out_root", type=str, default="corner_images_controlnet")

    args, _ = parser.parse_known_args(argv)
    prompt = args.prompt
    imageURL = args.imageURL

    if "?" in imageURL:
        imageURL = imageURL[: imageURL.index("?")]

    container_name = args.container_name

    # Load image and resize to SD1.5 inpaint-friendly size
    init_image = load_image(imageURL).convert("RGB").resize((512, 512))

    # Mask: user-provided or default
    if args.mask_path:
        mask_image = Image.open(args.mask_path).convert("L").resize((512, 512))
    elif args.maskURL:
        mask_image = load_image(args.maskURL).convert("L").resize((512, 512))
    elif args.mask_preset: # Use preset_mask if mask_preset is provided
        mask_image = preset_mask(args.mask_preset, (512, 512))
    else:
        # Fallback if no mask options are provided, though a preset is expected from the prompt
        print("Warning: No mask, maskURL, or mask_preset provided. Using an empty mask.")
        mask_image = Image.new("L", (512, 512), 0)

    control_image = make_inpaint_condition(init_image, mask_image)

    # Load models
    base_model = "stable-diffusion-v1-5/stable-diffusion-v1-5"
    controlnet_id = "lllyasviel/control_v11p_sd15_inpaint"

    dtype = torch.float16 if torch.cuda.is_available() else torch.float32

    controlnet = ControlNetModel.from_pretrained(controlnet_id, torch_dtype=dtype)

    pipe = StableDiffusionControlNetInpaintPipeline.from_pretrained(
        base_model,
        controlnet=controlnet,
        torch_dtype=dtype,
        safety_checker=None,
        requires_safety_checker=False,
    )


    pipe.scheduler = DDIMScheduler.from_config(pipe.scheduler.config)

    if torch.cuda.is_available():
        try:
            pipe.enable_model_cpu_offload()
        except Exception:
            pipe = pipe.to("cuda")
        pipe.enable_attention_slicing()
    else:
        pipe = pipe.to("cpu")

    gen = torch.Generator(device="cpu").manual_seed(args.seed)

    out = pipe(
        prompt=prompt,
        negative_prompt=args.negative_prompt,
        num_inference_steps=args.steps,
        guidance_scale=args.guidance,
        generator=gen,
        image=init_image,
        mask_image=mask_image,
        control_image=control_image,
    )

    image = out.images[0]

    #file name logic
    prompt_for_name = prompt
    promptCommaInd = prompt_for_name.index(",") if "," in prompt_for_name else len(prompt_for_name)
    prompt_for_name = prompt_for_name[:promptCommaInd]
    promptSplit = prompt_for_name.split(" ")

    base_name = os.path.basename(imageURL)
    name_no_ext = os.path.splitext(base_name)[0]
    prompt_joined = "_".join(promptSplit)

    new_filename = f"{name_no_ext}_cn_cc_{prompt_joined}_seed{args.seed}.png"

    parsed_url = urlparse(imageURL)
    path_segments = [segment for segment in parsed_url.path.split("/") if segment]

    try:
        container_idx = path_segments.index(container_name)
    except ValueError:
        print(f"Warning: Container name '{container_name}' not found in the URL path. Saving to 'corner_images_controlnet/default_output/'.")
        blob_output_dir_components = ["default_output"]
    else:
        blob_output_dir_components = path_segments[container_idx:-1]

        if blob_output_dir_components:
            blob_output_dir_components[-1] = "corner_cases"
        else:
            blob_output_dir_components = [container_name, "corner_cases"]

    imageFilepath = os.path.abspath(args.out_root)
    imageFilepath += "/" + "/".join(blob_output_dir_components)
    os.makedirs(imageFilepath, exist_ok=True)
    imageFilepath += "/" + new_filename

    image.save(imageFilepath)
    print(imageFilepath)


if __name__ == "__main__":
    main()