version: '3.8'

services:
  saas:
    build:
      context: ..
      dockerfile: docker/Dockerfile-saas
      target: development
    container_name: datara-saas
    environment:
      DATARA_API_BASE_URL: http://backend:5000
    working_dir: /app
    volumes:
      - ..:/app
    stdin_open: true
    tty: true
    networks:
      - datara-network
    restart: unless-stopped
    command: ["sleep", "infinity"]

networks:
  datara-network:
    external: true
